Added the option for image to take it original size
AllenDang/giu pull request #815
Opened 2024-07-08 16:10 UTC by MisustinIvan

you can now do .Size(0,0) and the image takes its original size

2024-07-08 16:19 UTC, MisustinIvan commented
Because i am not if there is a way to do this without this change if you use image from URL. You can of course just write your own function that fetches the image and gets the size, but whats the point of ImageWithURLWidget? I was also thinking about adding a option to set a size constraint and just scale the image while keeping the aspect ratio to fit the constraint. It would be nice if you shared some feedback, thanks!

2024-07-08 20:46 UTC, MisustinIvan commented
I have also thought about replacing the behavior when passing in (-1, -1) to Size with this, because the current one kinda sucks and just stretches the Image.

2024-07-09 13:13 UTC, MisustinIvan commented on ImageWidgets.go
> +	if width == 0 && height == 0 {
sure, will fix that!

2024-07-09 13:18 UTC, MisustinIvan commented on ImageWidgets.go
> +
is there a way for me to see CI runs in my fork? Do i just create my own workflows?

2024-07-09 14:29 UTC, MisustinIvan commented
And would you be able to recommend me some things to work on in this project? I find it quite cool and would like to contribute some more. :smile:

2024-07-10 06:05 UTC, gucio321 requested changes
2 more things:
- could you wite a comment over ImageWidget (and probably ImageWithURL and other Image*` type definition and describe what `0` does
- there is still one liner issue

2024-07-10 06:05 UTC, gucio321 commented on ImageWidgets.go
> +
linter still complains here

2024-07-10 06:22 UTC, gucio321 commented
@MisustinIvan generally, we have 3 types of issues:
1. giu-related stuff - e.g. missing functions, some nice enhancements for API (or things like this PR). I've tagged them with https://github.com/AllenDang/giu/labels/good%20first%20issue
2. issues with cimgui-go (which are the worst sh*t I've ever seen :smile:). In general they are caused by our migration from imgui-go to cimgui-go and the fact that cimgui-go was/is early in development. It works but it requires some fixes.
3. well, we have one more _type of issue_: since migration in #628 I was forced to disable some widgets (e.g. CodeEditor, MarkdownEditor end so on). Now it'd be nice to re-enable them but it requires work on cimgui-go and even writing some C wrapers for C++ projects in lua (basing on https://github.com/cimgui like I did e.g. for markdown in https://github.com/gucio321/cimmarkdown)

2024-07-10 08:23 UTC, MisustinIvan commented
Bruh does the linter really want comments to end with period...

2024-07-10 08:31 UTC, MisustinIvan commented
Check passed, everything seems fine to me!

2024-07-10 10:52 UTC, gucio321 approved these changes
nice, thank you

2024-07-10 10:52 UTC, merged

2024-07-10 10:53 UTC, gucio321 commented
> Bruh does the linter really want comments to end with period...

you can use `golangci-lint run --fix ./...` and this should automatically fix that.

2024-07-10 11:04 UTC, gucio321 commented on ImageWidgets.go
> +
you should see them here:
![image](https://github.com/AllenDang/giu/assets/73652197/743a6d65-98c2-4bd1-86c1-3ee925bccf06)

2024-07-10 11:13 UTC, MisustinIvan commented
thanks, will try that next time!

2024-07-10 11:14 UTC, MisustinIvan commented
btw what is the best practice, github is asking me if I want to delete the feature branch. Should i delete it or keep it?

2024-07-10 11:35 UTC, gucio321 commented
I thing you should delete. these commits are in master anyway and if you keep every branch, you'll have hundreds of them some day :smile: